from .auth_routes import auth_routes
from .user_routes import user_routes
from .bookmarks import bookmark_routes
from .comments import comment_routes
from .follows import follow_routes
from .likes import like_routes
from .messages import message_routes
from .tweets import tweet_routes
from .files import file_routes
from .channels import channel_routes
from .notifications import notification_routes
